import { fileURLToPath } from 'node:url';
import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr_assets from 'aws-cdk-lib/aws-ecr-assets';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import type * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/** Header CloudFront adds and the ALB listener rule checks. */
export const ORIGIN_VERIFY_HEADER = 'X-Origin-Verify';
/** Container port the Fastify server listens on. */
export const APP_PORT = 8080;

/**
 * Paths kept out of the Docker build context (dockerignore syntax). `npm run
 * build` compiles src/ (including the generated src/sim/levels.generated.ts)
 * and public/ with tools/build.mjs + tools/lib.mjs; nothing else is needed.
 */
export const IMAGE_CONTEXT_EXCLUDE: readonly string[] = [
  'node_modules', 'dist', 'cdk.out', '.git', '.github', '.gitignore', '.claude', 'docs', 'test', 'levels',
  'tools/dev.mjs', 'tools/qa', 'tools/postdeploy.*', 'tools/icons.*', 'tools/release.*', 'tools/stats.*', 'tools/solve.ts', 'tools/hash-corpus.ts', 'infra', 'cdk.json', 'cdk.context.json',
  'cdk-outputs.json', 'vitest.config.ts', 'clawd-jump.tar.gz', 'LICENSE', '**/*.md', '*.log', '.env',
];

export interface ServiceProps {
  readonly vpc: ec2.IVpc;
  readonly albSubnets: ec2.SubnetSelection;
  readonly serviceSubnets: ec2.SubnetSelection;
  readonly assignPublicIp: boolean;
  /** `com.amazonaws.global.cloudfront.origin-facing` managed prefix list id for the region. */
  readonly cloudfrontPrefixListId: string;
  readonly desiredCount: number;
  readonly table: dynamodb.ITableV2;
  /** Docker build context; defaults to the repository root. */
  readonly imageDirectory?: string;
}

/**
 * ALB → ECS Fargate (Graviton) running the Fastify server.
 *
 * The ALB is internet-facing but its security group admits only CloudFront's
 * origin-facing prefix list, and the listener answers 403 unless the request
 * carries the `X-Origin-Verify` token. The token is generated by Secrets
 * Manager and only ever appears in the template as a dynamic reference.
 */
export class Service extends Construct {
  readonly cluster: ecs.Cluster;
  readonly service: ecs.FargateService;
  readonly loadBalancer: elbv2.ApplicationLoadBalancer;
  readonly listener: elbv2.ApplicationListener;
  readonly targetGroup: elbv2.ApplicationTargetGroup;
  readonly albSecurityGroup: ec2.SecurityGroup;
  readonly serviceSecurityGroup: ec2.SecurityGroup;
  /** Secrets Manager secret holding the origin-verify token. */
  readonly originToken: secretsmanager.Secret;
  /**
   * The token as a CloudFormation dynamic reference (`{{resolve:secretsmanager:…}}`).
   * Safe to embed in the template: CloudFormation resolves it at deploy time.
   */
  readonly originTokenValue: string;
  readonly dailySecret: secretsmanager.Secret;
  /** HMAC key for playerTag; the server falls back to DAILY_SECRET when unset. */
  readonly tagSecret: secretsmanager.Secret;
  readonly logGroup: logs.LogGroup;
  /** Content hash of the container image; exported to the app as APP_VERSION. */
  readonly imageHash: string;

  constructor(scope: Construct, id: string, props: ServiceProps) {
    super(scope, id);
    const stack = cdk.Stack.of(this);

    // --- secrets -----------------------------------------------------------
    this.originToken = new secretsmanager.Secret(this, 'OriginToken', {
      description: 'CLAWD ECHO TOWER: CloudFront to ALB X-Origin-Verify token',
      generateSecretString: { excludePunctuation: true, passwordLength: 40 },
    });
    // unsafeUnwrap() is the documented escape hatch: the rendered value is a
    // dynamic reference, not the plaintext secret.
    this.originTokenValue = this.originToken.secretValue.unsafeUnwrap();

    this.dailySecret = new secretsmanager.Secret(this, 'DailySecret', {
      description: 'CLAWD ECHO TOWER: HMAC key for daily tower seeds',
      generateSecretString: { excludePunctuation: true, passwordLength: 48 },
    });

    // Separate from DAILY_SECRET so either can rotate on its own: rotating this
    // one changes every playerTag, rotating DAILY_SECRET changes future seeds.
    this.tagSecret = new secretsmanager.Secret(this, 'TagSecret', {
      description: 'CLAWD ECHO TOWER: HMAC key for player tags',
      generateSecretString: { excludePunctuation: true, passwordLength: 48 },
    });

    // --- security groups ---------------------------------------------------
    this.albSecurityGroup = new ec2.SecurityGroup(this, 'AlbSg', {
      vpc: props.vpc,
      description: 'ALB: ingress only from the CloudFront origin-facing prefix list',
      allowAllOutbound: true,
    });
    this.albSecurityGroup.addIngressRule(
      ec2.Peer.prefixList(props.cloudfrontPrefixListId),
      ec2.Port.tcp(80),
      'CloudFront origin-facing',
    );

    this.serviceSecurityGroup = new ec2.SecurityGroup(this, 'ServiceSg', {
      vpc: props.vpc,
      description: 'Fargate tasks: ingress only from the ALB',
      allowAllOutbound: true,
    });
    this.serviceSecurityGroup.addIngressRule(this.albSecurityGroup, ec2.Port.tcp(APP_PORT), 'ALB to app');

    // --- load balancer -----------------------------------------------------
    this.loadBalancer = new elbv2.ApplicationLoadBalancer(this, 'Alb', {
      vpc: props.vpc,
      internetFacing: true,
      vpcSubnets: props.albSubnets,
      securityGroup: this.albSecurityGroup,
      idleTimeout: cdk.Duration.seconds(60),
    });

    this.targetGroup = new elbv2.ApplicationTargetGroup(this, 'Tg', {
      vpc: props.vpc,
      port: APP_PORT,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targetType: elbv2.TargetType.IP,
      deregistrationDelay: cdk.Duration.seconds(15),
      healthCheck: {
        path: '/healthz',
        healthyHttpCodes: '200',
        interval: cdk.Duration.seconds(15),
        timeout: cdk.Duration.seconds(5),
        healthyThresholdCount: 2,
        unhealthyThresholdCount: 3,
      },
    });

    // `open: false` keeps CDK from adding a 0.0.0.0/0 ingress rule to the SG.
    this.listener = this.loadBalancer.addListener('Http', {
      port: 80,
      protocol: elbv2.ApplicationProtocol.HTTP,
      open: false,
      defaultAction: elbv2.ListenerAction.fixedResponse(403, {
        contentType: 'text/plain',
        messageBody: 'Forbidden',
      }),
    });
    this.listener.addAction('Verified', {
      priority: 1,
      conditions: [elbv2.ListenerCondition.httpHeader(ORIGIN_VERIFY_HEADER, [this.originTokenValue])],
      action: elbv2.ListenerAction.forward([this.targetGroup]),
    });

    // --- container image ---------------------------------------------------
    const image = new ecr_assets.DockerImageAsset(this, 'Image', {
      directory: props.imageDirectory ?? fileURLToPath(new URL('../../../', import.meta.url)),
      file: 'Dockerfile',
      platform: ecr_assets.Platform.LINUX_ARM64,
      // Only what `npm run build` needs goes into the build context; everything
      // else would just churn the asset hash (and APP_VERSION) without changing
      // the image. Mirror of .dockerignore (CDK merges both). What remains:
      // package.json, package-lock.json, tsconfig.json, Dockerfile, src, public,
      // tools/build.mjs, tools/lib.mjs.
      exclude: [...IMAGE_CONTEXT_EXCLUDE],
    });
    this.imageHash = image.assetHash;

    // --- cluster / task ----------------------------------------------------
    this.cluster = new ecs.Cluster(this, 'Cluster', {
      vpc: props.vpc,
      containerInsightsV2: ecs.ContainerInsights.ENHANCED,
    });

    this.logGroup = new logs.LogGroup(this, 'Logs', {
      retention: logs.RetentionDays.TWO_WEEKS,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDef', {
      cpu: 256,
      memoryLimitMiB: 512,
      runtimePlatform: {
        cpuArchitecture: ecs.CpuArchitecture.ARM64,
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
      },
    });

    taskDefinition.addContainer('app', {
      containerName: 'app',
      image: ecs.ContainerImage.fromDockerImageAsset(image),
      portMappings: [{ containerPort: APP_PORT, protocol: ecs.Protocol.TCP }],
      logging: ecs.LogDrivers.awsLogs({ logGroup: this.logGroup, streamPrefix: 'app' }),
      environment: {
        NODE_ENV: 'production',
        PORT: String(APP_PORT),
        STATIC_DIR: '/app/dist/public',
        TABLE_NAME: props.table.tableName,
        AWS_REGION: stack.region,
        APP_VERSION: this.imageHash,
      },
      secrets: {
        DAILY_SECRET: ecs.Secret.fromSecretsManager(this.dailySecret),
        TAG_SECRET: ecs.Secret.fromSecretsManager(this.tagSecret),
      },
    });

    props.table.grantReadWriteData(taskDefinition.taskRole);

    // --- service -----------------------------------------------------------
    this.service = new ecs.FargateService(this, 'Service', {
      cluster: this.cluster,
      taskDefinition,
      desiredCount: props.desiredCount,
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      circuitBreaker: { enable: true, rollback: true },
      healthCheckGracePeriod: cdk.Duration.seconds(60),
      vpcSubnets: props.serviceSubnets,
      assignPublicIp: props.assignPublicIp,
      securityGroups: [this.serviceSecurityGroup],
    });
    this.service.attachToApplicationTargetGroup(this.targetGroup);

    const scaling = this.service.autoScaleTaskCount({ minCapacity: 2, maxCapacity: 6 });
    scaling.scaleOnCpuUtilization('Cpu', {
      targetUtilizationPercent: 60,
      scaleInCooldown: cdk.Duration.seconds(120),
      scaleOutCooldown: cdk.Duration.seconds(60),
    });
    scaling.scaleOnRequestCount('Requests', {
      requestsPerTarget: 400,
      targetGroup: this.targetGroup,
      scaleInCooldown: cdk.Duration.seconds(120),
      scaleOutCooldown: cdk.Duration.seconds(60),
    });
  }
}
